export const Blogs = [
  {
    id: 0,
    date: "15 June 2023",
    img: "https://www.cloudways.com/blog/wp-content/uploads/Trending-Products-to-Sell-Online-1.jpg",
    title: "Feature a Top-Selling Product",
    shortdesc:
      "Discover our hottest item of the season! Dive into the features that make it a customer favorite.",
    longdesc:
      "In this blog post, we shine a spotlight on our top-selling product, a true trendsetter in the world of online shopping. From its innovative design to its unmatched functionality, we delve into the reasons behind its popularity. Customer testimonials provide insights into how this product has exceeded expectations, making it a must-have for savvy shoppers. Get an exclusive look behind the scenes and discover the magic that makes this item a perennial favorite. Uncover the allure behind our top-selling product in this in-depth exploration. Beyond its sleek design and cutting-edge features, we delve into the customer experience, exploring the ways it seamlessly integrates into daily life. Peer into the reviews that sing praises of its transformative impact, and follow the journey from production to package, understanding why this product stands out in the vast landscape of online offerings. This is more than just an item; it's a phenomenon redefining online shopping.",
  },
  {
    id: 1,
    date: "30 July 2023",
    img: "https://d2ydtwisqcxv72.cloudfront.net/customerexperienceroadmap.png",
    title: "The Journey of a Product",
    shortdesc:
      "Uncover the fascinating journey from concept to your doorstep as we take you behind the scenes of our product development.",
    longdesc:
      "Embark on a captivating journey as we unveil the intricate process of bringing a product from concept to your doorstep. From the initial stages of brainstorming and design to the meticulous manufacturing process and rigorous quality control, every step is a testament to our commitment to delivering excellence. Join us in celebrating the dedication and creativity that go into each product, making it not just an item, but a story waiting to be shared. Join us on a captivating odyssey, tracing the intricate path a product takes before reaching your hands. From the initial spark of an idea to the meticulous crafting process, witness the dedication that goes into creating a product that transcends mere utility. Navigate the challenges faced during production, and celebrate the triumphs that result in a product worthy of your attention. This isn't just about what you buy; it's about the story each product carries with it.",
  },
  {
    id: 2,
    date: "12 Sep 2023",
    img: "https://blog.tubikstudio.com/wp-content/uploads/2016/09/tutorial_singify_tubik_illustration_flat_app_ios_design.png",
    title: "Getting the Most Out of Your App",
    shortdesc:
      "Elevate your shopping experience with these app tips and tricks!",
    longdesc:
      " Elevate your online shopping experience with our comprehensive guide to unlocking the full potential of our ecommerce app. Navigate effortlessly through the app's user-friendly interface, discover insider tips on finding the best deals, and explore features designed to streamline your shopping journey. From personalized recommendations to seamless checkout processes, this guide ensures you're equipped with the knowledge to make every interaction with our app a delightful and rewarding experience. Elevate your digital shopping experience with our comprehensive guide to navigating the features that make our app a retail powerhouse. Uncover hidden gems that enhance your interaction, from personalized recommendations that feel like a personal shopper to a checkout process so smooth it becomes an afterthought. This guide isn't just about using an app; it's about unlocking a world of convenience, discounts, and personalized service at your fingertips.",
  },
  {
    id: 3,
    date: "1 Oct 2023",
    img: "https://www.binaryfolks.com/media/13th%20jan%20blog%20header.png",
    title: "Real-Life Experiences",
    shortdesc:
      "Hear firsthand stories from our satisfied customers and discover the impact our app has had on their lives.",
    longdesc:
      "Step into the lives of our valued customers as they share their personal experiences with our ecommerce app. Through heartwarming anecdotes and genuine testimonials, discover how our platform has not only simplified their shopping but has become an integral part of their lifestyle. From finding the perfect gift to enjoying hassle-free returns, these stories highlight the meaningful connections our app creates, turning ordinary transactions into extraordinary moments. Join us in celebrating the diverse and inspiring journeys of our cherished community. Immerse yourself in the genuine narratives of our customers as they share the moments that define their relationship with our ecommerce app. From the joy of discovering a perfect find to the ease of resolving concerns with our customer service, these stories embody the essence of our platform. It's not just about transactions; it's about the human connections forged through seamless and satisfying shopping experiences. Join us in celebrating the rich tapestry of lives touched by our app.",
  },
];

export const SpecialProducts = [
  {
    id: 0,
    img: "https://crivellishopping.in/image/cache/data/Prodotti/diesel/dz7406-diesel-800x800.jpg",
    brand: "Diesel",
    title: "Diesel Watch DZ7396",
    rating: 4.2,
    price: 299,
    strike_price: 400,
    offer: "25%",
    products: 7,
    progressbar: 12,
  },
  {
    id: 1,
    img: "https://www.footshop.cz/blog/wp-content/uploads/2020/01/17.jpg",
    brand: "Nike",
    title: "Nike Air Mag",
    rating: 4.9,
    price: 16999,
    strike_price: 26000,
    offer: "15%",
    products: 5,
    progressbar: 5,
  },
  {
    id: 2,
    img: "https://i.gadgets360cdn.com/products/large/sony-ps5-649x800-1592631239.jpeg?downsize=*:360",
    brand: "Sony",
    title: "PlayStation 5",
    rating: 4.6,
    price: 499,
    strike_price: 650,
    offer: "20%",
    products: 13,
    progressbar: 20,
  },
];

export const Famous = [
  {
    id: 0,
    img: "https://www.asus.com/media/Odin/Websites/global/Series/9.png",
    title: "Laptops",
    subtitle: "More seamless kind of learning.",
    link: "/laptop",
  },
  {
    id: 1,
    img: "https://www.boat-lifestyle.com/cdn/shop/products/main1_65ff249b-c4f8-4dad-ae88-2aae76723ce2.png?v=1643477993",
    title: "Headphones",
    subtitle: "Brand new sound asset",
    link: "/headphone",
  },
  {
    id: 2,
    img: "https://www.tradeinn.com/f/13910/139105693/lenovo-tabua-tb-j616f-p11-6gb-128gb-11.jpg",
    title: "Tablets",
    subtitle: "Upgrade for multitaskers",
    link: "/tablet",
  },
  {
    id: 3,
    img: "https://www.thestreet.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY4NjM5NjMwMTE0Njk1MDYz/10-outrageously-expensive-mens-luxury-watches-on-amazon.jpg",
    title: "Watch",
    subtitle: "Time Keepers",
    link: "/watch",
  },
];

export const Featured = [
  {
    id: 0,
    brand: "MVMT",
    rating: 4.8,
    price: 169,
    img: "https://img.tatacliq.com/images/i8/658Wx734H/MP000000013328500_658Wx734H_202206040954211.jpeg",
    title: "MVMT bloom analog Womens Watch",
  },
  {
    id: 1,
    brand: "SAMSUNG",
    rating: 4.7,
    price: 499,
    img: "https://www.vietnam.vn/wp-content/uploads/2023/08/1691277244_317_Chinh-thuc-gioi-thieu-Samsung-Crystal-Vision-4K-TV.jpg",
    title: "SAMSUNG Crystal Vision(43 inch) UHD (4K) LED Smart TV",
  },
  {
    id: 2,
    brand: "boAt",
    rating: 4.5,
    price: 50,
    img: "https://cdn1.smartprix.com/rx-i2sJltxjP-w1200-h1200/2sJltxjP.jpg",
    title: "boAt Rockerz 558 Wireless Headphones",
  },
  {
    id: 3,
    brand: "Apple",
    rating: 4.8,
    price: 999,
    img: "https://www.rueducommerce.fr/media/produits/apple/apple-iphone-15-pro-max-6-7-5g-double-sim-1-to-blanc-titanium-3545068_1140x1140.jpeg",
    title: "iPhone 15 Pro Max 512GB White Titanium",
  },
];

// export const Watches = [
//   {
//     id: "0",
//     brand: "MVMT",
//     rating: 4.8,
//     price: 169,
//     img: "https://img.tatacliq.com/images/i8/658Wx734H/MP000000013328500_658Wx734H_202206040954211.jpeg",
//     title: "MVMT bloom analog Womens Watch",
//   },
//   {
//     id: 1,
//     brand: "MVMT",
//     rating: 4.2,
//     price: 99,
//     img: "https://images-static.nykaa.com/media/catalog/product/c/e/ce4339028000011-D_1.jpg?tr=w-500,pr-true",
//     title: "MVMT Chrono Round White dail Mens Watch",
//   },
//   {
//     id: 2,
//     brand: "MVMT",
//     rating: 4.5,
//     price: 159,
//     img: "https://m.media-amazon.com/images/I/611hfuQmCOL._AC_UY1000_.jpg",
//     title: "MVMT Blacktop analog Mens Watch",
//   },
//   {
//     id: 3,
//     brand: "MVMT",
//     rating: 4.3,
//     price: 119,
//     img: "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw7a617d02/images/products/FR01-RGGR_fr.jpg?sw=600&sh=600",
//     title: "MVMT Ghost Iris's grey Womens Watch",
//   },
//   {
//     id: 4,
//     brand: "MVMT",
//     rating: 4.3,
//     price: 119,
//     img: "https://www.watchesnjewellery.com/custom/page/page_content_img/712133/274723_28000030-D.jpg?width=1000&height=1000",
//     title: "MVMT 28000030-D LADIES WATCH",
//   },
//   {
//     id: 5,
//     brand: "MVMT",
//     rating: 4.1,
//     price: 99,
//     img: "https://images-static.nykaa.com/media/catalog/product/7/e/7ea5390D-MC01GML_1.jpg?tr=w-500,pr-true",
//     title: "MVMT Chrono Round Black dail Mens Watch",
//   },
//   {
//     id: 6,
//     brand: "MVMT",
//     rating: 4.4,
//     price: 169,
//     img: "https://images-static.nykaa.com/media/catalog/product/5/9/5903390D-MC01-GU_1.jpg?tr=w-500,pr-true",
//     title: "MVMT Black Round dail Mens Watch",
//   },
//   {
//     id: 7,
//     brand: "MVMT",
//     rating: 4.1,
//     price: 119,
//     img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTELLM9ivDrNCtBQfJilMUPWy7qk2FoyUWFlJh0961qJ4s7RVnMo3ydmuODK9YvCkifnYk&usqp=CAU",
//     title: "MVMT Ghost Iris's orange Womens Watch",
//   },
//   {
//     id: 8,
//     brand: "MVMT",
//     rating: 4.7,
//     price: 179,
//     img: "https://m.media-amazon.com/images/I/61Q0nWji8HL._AC_UY1000_.jpg",
//     title: "MVMT Bloom Analog White Dial Womens Watch",
//   },
//   {
//     id: 9,
//     brand: "MVMT",
//     rating: 4.3,
//     price: 99,
//     img: "https://images-static.nykaa.com/media/catalog/product/0/7/0748390D-MC01-WBTL_1.jpg?tr=w-500,pr-true",
//     title: "MVMT Chrono Round White dail Mens Watch",
//   },
//   {
//     id: 10,
//     brand: "MVMT",
//     rating: 4.8,
//     price: 179,
//     img: "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw6a1ec892/images/products/28000284_fr.jpg?sw=600&sh=600",
//     title: "MVMT Chrono Ceramic Mens Watch Fog grey",
//   },
//   {
//     id: 11,
//     brand: "MVMT",
//     rating: 4.2,
//     price: 129,
//     img: "https://rukminim2.flixcart.com/image/850/1000/l33cia80/watch/e/p/n/1-d-mb01-rggr-mvmt-women-original-imageah42zeqgcpq.jpeg?q=20",
//     title: "MVMT Boulevard Analog Watch - For Women",
//   },
// ];

// export const Laptops = [
//   {
//     id: "0",
//     brand: "Apple",
//     rating: 4.6,
//     price: 3599,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/y/i/y/mphg3hn-a-thin-and-light-laptop-apple-original-imagmfhepavqyfyy.jpeg?q=70",
//     title: "MacBook Pro M2 Max (32 GB/1 TB SSD) (14 Inch, 1.63 Kg)",
//   },
//   {
//     id: 1,
//     brand: "Apple",
//     rating: 4.4,
//     price: 3899,
//     img: "https://rukminim2.flixcart.com/image/416/416/kuyf8nk0/computer/g/z/q/mk1e3hn-a-laptop-apple-original-imag7yzmv57cvg3f.jpeg?q=70",
//     title: "Macbook Pro M1 Max - (32 GB/1 TB SSD)",
//   },
//   {
//     id: 2,
//     brand: "HP",
//     rating: 4.5,
//     price: 899,
//     img: "https://rukminim2.flixcart.com/image/416/416/kwdv3bk0/computer/r/m/c/15-ec2145ax-gaming-laptop-hp-original-imag92vp9cznphgg.jpeg?q=70",
//     title: "HP Pavilion (8 GB/512 GB SSD) (15.6 inch, 1.98 kg)",
//   },
//   {
//     id: 3,
//     brand: "Apple",
//     rating: 4.8,
//     price: 3099,
//     img: "https://rukminim2.flixcart.com/image/416/416/kuyf8nk0/computer/g/z/q/mk1e3hn-a-laptop-apple-original-imag7yzmv57cvg3f.jpeg?q=70",
//     title: "Macbook Pro M1 Pro (16 GB/1 TB SSD) (16.2 inch, 2.1 kg)",
//   },
//   {
//     id: 4,
//     brand: "HP",
//     rating: 4.2,
//     price: 399,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/g/n/j/-original-imaguegfkhrkykxb.jpeg?q=70",
//     title: "HP 2023 Ryzen 3 (8 GB/512 GB SSD) (15.6 Inch, 1.69 Kg)",
//   },
//   {
//     id: 5,
//     brand: "Lenovo",
//     rating: 4,
//     price: 249,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/screen-guard/screen-guard/4/b/d/asg-14715-saco-original-imaghqbah9jycshw.jpeg?q=70",
//     title: "Lenovo Lenovo V15 Celeron (8 GB/256 GB SSD) (15.6 inch)",
//   },
//   {
//     id: 6,
//     brand: "Infinix",
//     rating: 4.2,
//     price: 299,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/u/u/k/-original-imagmxuravjcmdwu.jpeg?q=70",
//     title: "INBook Y1 Plus (8 GB/256 GB SSD) (15.6 inch, 1.76 kg)",
//   },
//   {
//     id: 7,
//     brand: "Acer",
//     rating: 4.2,
//     price: 339,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/6/5/g/-original-imagtke7erkzwzfp.jpeg?q=70",
//     title: "Acer One (8 GB/512 GB SSD) (14 Inch, 1.49 Kg)",
//   },
//   {
//     id: 8,
//     brand: "ASUS",
//     rating: 4.8,
//     price: 3499,
//     img: "https://rukminim2.flixcart.com/image/416/416/l58iaa80/computer/5/q/p/gx650rm-ls019ws-gaming-laptop-asus-original-imagfyg8tkytthbb.jpeg?q=70",
//     title: "Zephyrus Dual Screen (32 GB /2 TB SSD) (16 Inch, 2.50 Kg)",
//   },
//   {
//     id: 9,
//     brand: "ASUS",
//     rating: 4.4,
//     price: 729,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/g/n/i/m1603qa-mb712ws-notebook-asus-original-imagghmes5azfudv.jpeg?q=70",
//     title: "ASUS Vivobook (16 GB/512 GB SSD) (16 inch, 1.8 kg)",
//   },
//   {
//     id: 10,
//     brand: "HP",
//     rating: 3.7,
//     price: 229,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/c/e/f/-original-imaguegytjhxdfdf.jpeg?q=70",
//     title: "HP intel Celeron (4 GB/64 GB) (14 Inch, 1.46 kg)",
//   },
//   {
//     id: 11,
//     brand: "Infinix",
//     rating: 4.2,
//     price: 379,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/i/1/h/inbook-thin-and-light-laptop-infinix-original-imagpyjexehgq3kg.jpeg?q=70",
//     title: "Inbook X2 Slim (16 GB/512 GB SSD) (14 inch, 1.24 kg)",
//   },
// ];

// export const Tablets = [
//   {
//     id: 0,
//     brand: "Apple",
//     rating: 4.6,
//     price: 2999,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/l/1/d/-original-imagj73ytqpahjcj.jpeg?q=70",
//     title:
//       "APPLE iPad Pro (6th Gen) 2 TB ROM 12.9 inch with Wi-Fi+5G (Space Grey)",
//   },
//   {
//     id: 1,
//     brand: "Apple",
//     rating: 4.6,
//     price: 2499,
//     img: "https://rukminim2.flixcart.com/image/416/416/kolsscw0/tablet/n/r/c/mhwd3hn-a-apple-original-imag3yr5xrqchvrg.jpeg?q=70",
//     title:
//       "APPLE iPad Pro (5th Generation) 2 TB ROM 12.9 inches with Wi-Fi Only (Silver)",
//   },
//   {
//     id: 2,
//     brand: "SAMSUNG",
//     rating: 4.7,
//     price: 1099,
//     img: "https://rukminim2.flixcart.com/image/416/416/kzrbiq80/tablet/9/j/r/-original-imagbpez78varpjn.jpeg?q=70",
//     title:
//       "SAMSUNG Galaxy Tab S8+ 128 GB ROM 12.4 inch with Wi-Fi+5G Tablet (Pink Gold)",
//   },
//   {
//     id: 3,
//     brand: "Apple",
//     rating: 4.6,
//     price: 1120,
//     img: "https://rukminim2.flixcart.com/image/416/416/l0jwbrk0/tablet/h/l/f/-original-imagcbjgzhfak2jd.jpeg?q=70",
//     title:
//       "APPLE iPad Air (5th gen) 256 GB ROM 10.9 Inch with Wi-Fi+5G (Purple)",
//   },
//   {
//     id: 4,
//     brand: "Apple",
//     rating: 4.6,
//     price: 999,
//     img: "https://rukminim2.flixcart.com/image/416/416/ktop5e80/tablet/y/j/o/mk893hn-a-apple-original-imag6yg2hgqafged.jpeg?q=70",
//     title:
//       "APPLE iPad mini (6th Gen) 256 GB ROM 8.3 inch with Wi-Fi+5G (Space Grey)",
//   },
//   {
//     id: 5,
//     brand: "Lenovo",
//     rating: 4.3,
//     price: 729,
//     img: "https://rukminim2.flixcart.com/image/416/416/kl175ow0/tablet/t/1/x/za7d0021in-lenovo-original-imagy8w3ycyw2wm7.jpeg?q=70",
//     title:
//       "Lenovo Tab P11 Pro 6 GB RAM 128 GB ROM 11.5 inch with Wi-Fi+4G Tablet (Slate Grey)",
//   },
//   {
//     id: 6,
//     brand: "SAMSUNG",
//     rating: 4.5,
//     price: 579,
//     img: "https://rukminim2.flixcart.com/image/416/416/kq5iykw0/tablet/i/x/z/sm-t735nzsainu-samsung-original-imag48ffsvjayz3x.jpeg?q=70",
//     title:
//       "SAMSUNG Galaxy Tab S7 64 GB ROM 12.4 inches with Wi-Fi+4G Tablet (Silver)",
//   },
//   {
//     id: 7,
//     brand: "OnePlus",
//     rating: 4.6,
//     price: 479,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/c/s/v/opd2203-oneplus-original-imagzbd5h8ybgccv.jpeg?q=70",
//     title:
//       "OnePlus Pad 12 GB RAM 256 GB ROM 11.61 inch with Wi-Fi Only Tablet (Halo Green)",
//   },
//   {
//     id: 8,
//     brand: "realme",
//     rating: 4.4,
//     price: 349,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/y/a/y/-original-imaggfrhvghucswf.jpeg?q=70",
//     title:
//       "realme Pad X 6 GB RAM 128 GB ROM 11 inch with Wi-Fi+5G Tablet (Glacier Blue)",
//   },
//   {
//     id: 9,
//     brand: "MOTOROLA",
//     rating: 4.2,
//     price: 249,
//     img: "https://rukminim2.flixcart.com/image/416/416/kyag87k0/tablet/4/n/o/g70-lte-moto-original-imagak3huz7jweyz.jpeg?q=70",
//     title:
//       "MOTOROLA tab g70 LTE 64 GB ROM 11 inch with Wi-Fi+4G Tablet (Modernist Teal)",
//   },
//   {
//     id: 10,
//     brand: "Nokia",
//     rating: 4.2,
//     price: 200,
//     img: "https://rukminim2.flixcart.com/image/416/416/kvba7bk0/tablet/r/w/m/ta-1392-nokia-original-imag88wmgrhzzeyk.jpeg?q=70",
//     title:
//       "Nokia Tab T20 4GB RAM 64GB ROM 10.36 inch with Wi-Fi Only Tablet (Blue)",
//   },
//   {
//     id: 11,
//     brand: "Honor",
//     rating: 4.4,
//     price: 230,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/7/r/x/hey-w09-honor-original-imagg24vhgjym67v.jpeg?q=70",
//     title:
//       "Honor Pad 8 6 GB RAM 128 GB ROM 12 inch with Wi-Fi Only Tablet (Blue Hour)",
//   },
// ];

// export const Headphones = [
//   {
//     id: "0",
//     brand: "Sennheiser",
//     rating: 4.8,
//     price: 449,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/c/v/n/509266-sennheiser-original-imagj79ew44h3vzf.jpeg?q=70",
//     title:
//       "Sennheiser Momentum 4 Wireless ANC Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 1,
//     brand: "Beats",
//     rating: 3.9,
//     price: 299,
//     img: "https://rukminim2.flixcart.com/image/416/416/jvy4vbk0/headphone/d/z/n/beats-mrq82zm-a-original-imafgqhubwnzdyzq.jpeg?q=70",
//     title:
//       "Beats Studio3 Class 1, ANC Bluetooth Headset  (Defiant Black, Red, On the Ear)",
//   },
//   {
//     id: 2,
//     brand: "Bose",
//     rating: 4.4,
//     price: 279,
//     img: "https://rukminim2.flixcart.com/image/416/416/krs40i80/headphone/6/s/q/noise-cancelling-700-bose-original-imag5gf6uyakqjgg.jpeg?q=70",
//     title:
//       "Bose NOISE CANCELLING HDPHS 700, Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 3,
//     brand: "Beats",
//     rating: 4.2,
//     price: 299,
//     img: "https://rukminim2.flixcart.com/image/416/416/kiow6fk0-0/headphone/v/9/w/mrj82zm-a-beats-original-imafyfjyg7p3gwht.jpeg?q=70",
//     title: "Beats MRJ82ZM/A Bluetooth Headset  (Grey, On the Ear)",
//   },
//   {
//     id: 4,
//     brand: "JBL",
//     rating: 3.8,
//     price: 250,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/h/9/t/-original-imaguzgz4qjc5hnv.jpeg?q=70",
//     title: "JBL Tour One M2, ANC, Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 5,
//     brand: "SONY",
//     rating: 4.6,
//     price: 245,
//     img: "https://rukminim2.flixcart.com/image/416/416/l1dwknk0/headphone/b/f/2/wh-1000xm4-sony-original-imagcywfhzq8hx2z.jpeg?q=70",
//     title: "SONY WH-1000XM4 Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 6,
//     brand: "Logitech",
//     rating: 4.4,
//     price: 149,
//     img: "https://rukminim2.flixcart.com/image/416/416/l111lzk0/headphone/8/i/6/g733-lightspeed-rgb-logitech-original-imagcznej6g3z3th.jpeg?q=70",
//     title:
//       "Logitech G733 LIGHTSPEED RGB Bluetooth Headset  (Lilac, On the Ear)",
//   },
//   {
//     id: 7,
//     brand: "PHILIPS",
//     rating: 3.4,
//     price: 199,
//     img: "https://rukminim2.flixcart.com/image/416/416/k5zn9u80/headphone/k/t/s/philips-taph805bk-original-imafzjzsns62zqvj.jpeg?q=70",
//     title:
//       "PHILIPS TAPH805BK/10 Wireless, ANC Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 8,
//     brand: "JBL",
//     rating: 4,
//     price: 99,
//     img: "https://rukminim2.flixcart.com/image/416/416/kflftzk0pkrrdj/headphone-refurbished/g/n/u/u-quantum-200-jbl-original-imafw3z69hzxgynv.jpeg?q=70",
//     title: "JBL Quantum 200 Wired Gaming Headset  (Black, On the Ear)",
//   },
//   {
//     id: 9,
//     brand: "MOTOROLA",
//     rating: 3.4,
//     price: 129,
//     img: "https://rukminim2.flixcart.com/image/416/416/jt4olu80/headphone/t/u/g/motorola-escape-800-anc-original-imafejrmhqpgufyh.jpeg?q=70",
//     title: "MOTOROLA Escape 800 ANC Bluetooth Headset  (Black, On the Ear)",
//   },
//   {
//     id: 10,
//     brand: "boAt",
//     rating: 4.2,
//     price: 99,
//     img: "https://rukminim2.flixcart.com/image/416/416/kvsfhjk0/headphone/g/o/d/-original-imag8mf8xncrfjev.jpeg?q=70",
//     title: "boAt Rockerz 450 Pro Bluetooth Headset  (White, On the Ear)",
//   },
//   {
//     id: 11,
//     brand: "boAt",
//     rating: 4.5,
//     price: 50,
//     img: "https://cdn1.smartprix.com/rx-i2sJltxjP-w1200-h1200/2sJltxjP.jpg",
//     title: "boAt Rockerz 558 Wireless Headphones",
//   },
// ];

// export const Earbuds = [
//   {
//     id: 0,
//     brand: "OPPO",
//     rating: 4.2,
//     price: 49,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/p/r/z/enco-buds-2-oppo-original-imagh9frfp7gxdb3.jpeg?q=70",
//     title:
//       "OPPO Enco Buds 2 with 28 hours Battery life (Midnight, True Wireless)",
//   },
//   {
//     id: 1,
//     brand: "realme",
//     rating: 4.2,
//     price: 45,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/h/2/k/-original-imaghe5mtuu35bhk.jpeg?q=70",
//     title:
//       "realme Techlife Buds T100 with 28 Hours Playback & AI ENC (Blue, True Wireless)",
//   },
//   {
//     id: 2,
//     brand: "OnePlus",
//     rating: 4.3,
//     price: 59,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/w/t/q/-original-imagr4t8zuq2wzhe.jpeg?q=70",
//     title:
//       "OnePlus Nord Buds 2r in Ear Earbuds with Dual Mic (Deep Grey, True Wireless)",
//   },
//   {
//     id: 3,
//     brand: "Noise",
//     rating: 4,
//     price: 19,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/m/r/w/-original-imagsp8naj6v6ftm.jpeg?q=70",
//     title: "Noise Buds VS404 with 50 Hours Playtime (Jet Black, True Wireless)",
//   },
//   {
//     id: 4,
//     brand: "Boult",
//     rating: 4.1,
//     price: 25,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/z/v/y/-original-imagmuggusa94g3u.jpeg?q=70",
//     title:
//       "Boult Audio Z40 with Zen ENC Mic, 60H Battery Life (Blue, In the Ear)",
//   },
//   {
//     id: 5,
//     brand: "realme",
//     rating: 4.3,
//     price: 39,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/1/x/j/-original-imagsgfbgrfhy7vm.jpeg?q=70",
//     title:
//       "realme Buds Air 5 with 50dB ANC upto 38 hours (Deep Sea Blue, True Wireless)",
//   },
//   {
//     id: 6,
//     brand: "boAt",
//     rating: 4,
//     price: 19,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/1/8/l/-original-imagqhswqgpwb2yu.jpeg?q=70",
//     title: "boAt Airdopes 131 with upto 60 Hours (Active Black, True Wireless)",
//   },
//   {
//     id: 7,
//     brand: "Noise",
//     rating: 4.1,
//     price: 20,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/9/g/g/-original-imagufh6ghgms8nz.jpeg?q=70",
//     title:
//       "Noise Buds VS102 Neo with 40 Hrs Playtime (Carbon Black, True Wireless)",
//   },
//   {
//     id: 8,
//     brand: "realme",
//     rating: 4.3,
//     price: 30,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/v/y/o/-original-imagt3vwuweuwk9v.jpeg?q=70",
//     title:
//       "realme Buds T300 with 30dB ANC, 40 hours Playback   (Stylish Black, True Wireless)",
//   },
//   {
//     id: 9,
//     brand: "Apple",
//     rating: 4.6,
//     price: 279,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/e/a/f/-original-imagtc44nk4b3hfg.jpeg?q=70",
//     title:
//       "AirPods Pro (2nd generation) with MagSafe Case (USB-C) (White, True Wireless)",
//   },
//   {
//     id: 10,
//     brand: "Boult",
//     rating: 4.1,
//     price: 29,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/z/l/l/-original-imagty9c5pmq8tdt.jpeg?q=70",
//     title: "Boult Audio Astra with 48Hrs Battery  (Smoky Metal, True Wireless)",
//   },
//   {
//     id: 11,
//     brand: "OnePlus",
//     rating: 4.3,
//     price: 32,
//     img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/0/v/m/nord-buds-2-oneplus-original-imagnwf7sgjetqwg.jpeg?q=70",
//     title:
//       "OnePlus Nord Buds 2 Earbuds with 25dB, ANC (Thunder Gray, True Wireless)",
//   },
// ];

export const Productsdata = [
// Watch 
  {
    id: "watchmvmt01",
    brand: "MVMT",
    rating: 4.8,
    price: 169,
    strike_price:259,
    offer:20,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Formal",
    dail:"Dail color: ",
    dail_color:"Tan light pink",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://img.tatacliq.com/images/i8/658Wx734H/MP000000013328500_658Wx734H_202206040954211.jpeg",
    title: "MVMT bloom analog Womens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt02",
    brand: "MVMT",
    rating: 4.2,
    price: 99,
    strike_price:199,
    offer:50,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://images-static.nykaa.com/media/catalog/product/c/e/ce4339028000011-D_1.jpg?tr=w-500,pr-true",
    title: "MVMT Chrono Round White dail Mens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt03",
    brand: "MVMT",
    rating: 4.5,
    price: 159,
    strike_price:399,
    offer:62,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Formal",
    dail:"Dail color: ",
    dail_color:"Olive Green",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://m.media-amazon.com/images/I/611hfuQmCOL._AC_UY1000_.jpg",
    title: "MVMT Blacktop analog Mens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt04",
    brand: "MVMT",
    rating: 4.3,
    price: 119,
    strike_price:299,
    offer:65,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw7a617d02/images/products/FR01-RGGR_fr.jpg?sw=600&sh=600",
    title: "MVMT Ghost Iris's grey Womens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt05",
    brand: "MVMT",
    rating: 4.3,
    price: 119,
    strike_price:299,
    offer:65,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Party",
    dail:"Dail color: ",
    dail_color:"Tan light pink",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://www.watchesnjewellery.com/custom/page/page_content_img/712133/274723_28000030-D.jpg?width=1000&height=1000",
    title: "MVMT 28000030-D LADIES WATCH",
    category: "watch",
  },
  {
    id: "watchmvmt06",
    brand: "MVMT",
    rating: 4.1,
    price: 99,
    strike_price:199,
    offer:50,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"Black",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://images-static.nykaa.com/media/catalog/product/7/e/7ea5390D-MC01GML_1.jpg?tr=w-500,pr-true",
    title: "MVMT Chrono Round Black dail Mens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt07",
    brand: "MVMT",
    rating: 4.4,
    price: 169,
    strike_price:299,
    offer:47,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Formal",
    dail:"Dail color: ",
    dail_color:"Black",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://images-static.nykaa.com/media/catalog/product/5/9/5903390D-MC01-GU_1.jpg?tr=w-500,pr-true",
    title: "MVMT Black Round dail Mens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt08",
    brand: "MVMT",
    rating: 4.1,
    price: 119,
    strike_price:299,
    offer:65,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTELLM9ivDrNCtBQfJilMUPWy7qk2FoyUWFlJh0961qJ4s7RVnMo3ydmuODK9YvCkifnYk&usqp=CAU",
    title: "MVMT Ghost Iris's orange Womens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt09",
    brand: "MVMT",
    rating: 4.7,
    price: 179,
    strike_price:499,
    offer:70,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Formal",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://m.media-amazon.com/images/I/61Q0nWji8HL._AC_UY1000_.jpg",
    title: "MVMT Bloom Analog White Dial Womens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt10",
    brand: "MVMT",
    rating: 4.3,
    price: 99,
    strike_price:199,
    offer:50,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://images-static.nykaa.com/media/catalog/product/0/7/0748390D-MC01-WBTL_1.jpg?tr=w-500,pr-true",
    title: "MVMT Chrono Round White dail Mens Watch",
    category: "watch",
  },
  {
    id: "watchmvmt11",
    brand: "MVMT",
    rating: 4.8,
    price: 179,
    strike_price:499,
    offer:70,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Formal",
    dail:"Dail color: ",
    dail_color:"Ceramic White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw6a1ec892/images/products/28000284_fr.jpg?sw=600&sh=600",
    title: "MVMT Chrono Ceramic Mens Watch Fog grey",
    category: "watch",
  },
  {
    id: "watchmvmt12",
    brand: "MVMT",
    rating: 4.2,
    price: 129,
    strike_price:200,
    offer:45,
    display:"Display Type: ",
    display_type:"Analog",
    occasion:"Occasion: ",
    occasion_type:"Casual",
    dail:"Dail color: ",
    dail_color:"White",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/850/1000/l33cia80/watch/e/p/n/1-d-mb01-rggr-mvmt-women-original-imageah42zeqgcpq.jpeg?q=20",
    title: "MVMT Boulevard Analog Watch - For Women",
    category: "watch",
  },
// Laptop 
  {
    id: "laptopapple01",
    brand: "Apple",
    rating: 4.6,
    price: 3599,
    strike_price:4599,
    offer:20,
    processor:"Processor: ",
    processor_name:"M2 Max",
    ram:"RAM | SSD Storage: ",
    ram_type:"32GB | 1TB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Mac OS",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/y/i/y/mphg3hn-a-thin-and-light-laptop-apple-original-imagmfhepavqyfyy.jpeg?q=70",
    title: "MacBook Pro M2 Max (32 GB/1 TB SSD) (14 Inch, 1.63 Kg)",
    category: "laptop",
  },
  {
    id: "laptopapple02",
    brand: "Apple",
    rating: 4.4,
    price: 3899,
    strike_price:4999,
    offer:17,
    processor:"Processor: ",
    processor_name:"M1 Max",
    ram:"RAM | SSD Storage: ",
    ram_type:"32GB | 1TB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Mac OS",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kuyf8nk0/computer/g/z/q/mk1e3hn-a-laptop-apple-original-imag7yzmv57cvg3f.jpeg?q=70",
    title: "Macbook Pro M1 Max - (32 GB/1 TB SSD)",
    category: "laptop",
  },
  {
    id: "laptophp03",
    brand: "HP",
    rating: 4.5,
    price: 899,
    strike_price:999,
    offer:10,
    processor:"Processor: ",
    processor_name:"AMD Ryzen 5 Hexa Core",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 512 GB",
    screen:"Screen size: ",
    screen_size:"15.6 Inch",
    os:"OS: ",
    os_type:"Windows 10",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kwdv3bk0/computer/r/m/c/15-ec2145ax-gaming-laptop-hp-original-imag92vp9cznphgg.jpeg?q=70",
    title: "HP Pavilion (8 GB/512 GB SSD) (15.6 inch, 1.98 kg)",
    category: "laptop",
  },
  {
    id: "laptopapple04",
    brand: "Apple",
    rating: 4.8,
    price: 3099,
    strike_price:4099,
    offer:15,
    processor:"Processor: ",
    processor_name:"M1 Pro",
    ram:"RAM | SSD Storage: ",
    ram_type:"16 GB | 1 TB",
    screen:"Screen size: ",
    screen_size:"16.2 Inch",
    os:"OS: ",
    os_type:"Mac OS",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kuyf8nk0/computer/g/z/q/mk1e3hn-a-laptop-apple-original-imag7yzmv57cvg3f.jpeg?q=70",
    title: "Macbook Pro M1 Pro (16 GB/1 TB SSD) (16.2 inch, 2.1 kg)",
    category: "laptop",
  },
  {
    id: "laptophp05",
    brand: "HP",
    rating: 4.2,
    price: 399,
    strike_price:599,
    offer:30,
    processor:"Processor: ",
    processor_name:"AMD Ryzen 3 Quad Core",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 512GB",
    screen:"Screen size: ",
    screen_size:"15.6 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/g/n/j/-original-imaguegfkhrkykxb.jpeg?q=70",
    title: "HP 2023 Ryzen 3 (8 GB/512 GB SSD) (15.6 Inch, 1.69 Kg)",
    category: "laptop",
  },
  {
    id: "laptoplenovo06",
    brand: "Lenovo",
    rating: 4,
    price: 249,
    strike_price:499,
    offer:25,
    processor:"Processor: ",
    processor_name:"Intel Celeron Dual Core 4th Gen",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 256GB",
    screen:"Screen size: ",
    screen_size:"15.6 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/screen-guard/screen-guard/4/b/d/asg-14715-saco-original-imaghqbah9jycshw.jpeg?q=70",
    title: "Lenovo Lenovo V15 Celeron (8 GB/256 GB SSD) (15.6 inch)",
    category: "laptop",
  },
  {
    id: "laptopinfinix07",
    brand: "Infinix",
    rating: 4.2,
    price: 299,
    strike_price:499,
    offer:27,
    processor:"Processor: ",
    processor_name:"Intel Core i3 10th Gen",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 256GB",
    screen:"Screen size: ",
    screen_size:"15.6 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/u/u/k/-original-imagmxuravjcmdwu.jpeg?q=70",
    title: "INBook Y1 Plus (8 GB/256 GB SSD) (15.6 inch, 1.76 kg)",
    category: "laptop",
  },
  {
    id: "laptopacer08",
    brand: "Acer",
    rating: 4.2,
    price: 339,
    strike_price:599,
    offer:16,
    processor:"Processor: ",
    processor_name:"Intel Core i3 11th Gen",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 512GB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/6/5/g/-original-imagtke7erkzwzfp.jpeg?q=70",
    title: "Acer One (8 GB/512 GB SSD) (14 Inch, 1.49 Kg)",
    category: "laptop",
  },
  {
    id: "laptopasus09",
    brand: "ASUS",
    rating: 4.8,
    price: 3499,
    strike_price:5000,
    offer:23,
    processor:"Processor: ",
    processor_name:"AMD Ryzen 9 16 Core",
    ram:"RAM | SSD Storage: ",
    ram_type:"32GB | 2TB",
    screen:"Screen size: ",
    screen_size:"16 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/l58iaa80/computer/5/q/p/gx650rm-ls019ws-gaming-laptop-asus-original-imagfyg8tkytthbb.jpeg?q=70",
    title: "Zephyrus Dual Screen (32 GB /2 TB SSD) (16 Inch, 2.50 Kg)",
    category: "laptop",
  },
  {
    id: "laptopasus10",
    brand: "ASUS",
    rating: 4.4,
    price: 729,
    strike_price:999,
    offer:12,
    processor:"Processor: ",
    processor_name:"Intel Core i3 11th Gen",
    ram:"RAM | SSD Storage: ",
    ram_type:"8GB | 512GB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/g/n/i/m1603qa-mb712ws-notebook-asus-original-imagghmes5azfudv.jpeg?q=70",
    title: "ASUS Vivobook (16 GB/512 GB SSD) (16 inch, 1.8 kg)",
    category: "laptop",
  },
  {
    id: "laptophp11",
    brand: "HP",
    rating: 3.7,
    price: 229,
    strike_price:499,
    offer:18,
    processor:"Processor: ",
    processor_name:"Intel Celeron Dual Core",
    ram:"RAM | SSD Storage: ",
    ram_type:"4GB | 64GB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Chrome",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/c/e/f/-original-imaguegytjhxdfdf.jpeg?q=70",
    title: "HP intel Celeron (4 GB/64 GB) (14 Inch, 1.46 kg)",
    category: "laptop",
  },
  {
    id: "laptopinfinix12",
    brand: "Infinix",
    rating: 4.2,
    price: 379,
    strike_price:899,
    offer:17,
    processor:"Processor: ",
    processor_name:"Intel Core i5 11th Gen",
    ram:"RAM | SSD Storage: ",
    ram_type:"16GB | 512GB",
    screen:"Screen size: ",
    screen_size:"14 Inch",
    os:"OS: ",
    os_type:"Windows 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Onsite Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/computer/i/1/h/inbook-thin-and-light-laptop-infinix-original-imagpyjexehgq3kg.jpeg?q=70",
    title: "Inbook X2 Slim (16 GB/512 GB SSD) (14 inch, 1.24 kg)",
    category: "laptop",
  },

  {
    id: "tabapple01",
    brand: "Apple",
    rating: 4.6,
    price: 2999,
    strike_price:3500,
    offer:15,
    processor:"Processor: ",
    processor_name:"M2 chip",
    ram:"RAM | SSD Storage: ",
    ram_type:"2TB ROM",
    screen:"Screen size: ",
    screen_size:"12.9 Inch",
    os:"OS: ",
    os_type:"IPadOS 16",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/l/1/d/-original-imagj73ytqpahjcj.jpeg?q=70",
    title:"APPLE iPad Pro (6th Gen) 2 TB ROM 12.9 inch with Wi-Fi+5G (Space Grey)",
    category:"tab"
  },
  {
    id: "tabapple02",
    brand: "Apple",
    rating: 4.6,
    price: 2499,
    strike_price:3000,
    offer:15,
    processor:"Processor: ",
    processor_name:"M1 chip",
    ram:"RAM | SSD Storage: ",
    ram_type:"16 GB RAM | 2 TB ROM",
    screen:"Screen size: ",
    screen_size:"12.9 Inch",
    os:"OS: ",
    os_type:"iPadOS 14",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kolsscw0/tablet/n/r/c/mhwd3hn-a-apple-original-imag3yr5xrqchvrg.jpeg?q=70",
    title:"APPLE iPad Pro (5th Generation) 2 TB ROM 12.9 inches with Wi-Fi Only (Silver)",
    category:"tab"
  },
  {
    id: "tabsamsung03",
    brand: "SAMSUNG",
    rating: 4.7,
    price: 1099,
    strike_price:1999,
    offer:40,
    processor:"Processor: ",
    processor_name:"Snapdragon 8 Gen 2",
    ram:"RAM | SSD Storage: ",
    ram_type:"128GB ROM",
    screen:"Screen size: ",
    screen_size:"12.4 Inch",
    os:"OS: ",
    os_type:"Android",
    warranty:"Warranty: ",
    warranty_years:"1 Year",
    img: "https://rukminim2.flixcart.com/image/416/416/kzrbiq80/tablet/9/j/r/-original-imagbpez78varpjn.jpeg?q=70",
    title:"SAMSUNG Galaxy Tab S8+ 128 GB ROM 12.4 inch with Wi-Fi+5G Tablet (Pink Gold)",
    category:"tab"
  },
  {
    id: "tabapple04",
    brand: "Apple",
    rating: 4.6,
    price: 1120,
    strike_price:1999,
    offer:25,
    processor:"Processor: ",
    processor_name:"M1 chip",
    ram:"RAM | SSD Storage: ",
    ram_type:"256GB ROM",
    screen:"Screen size: ",
    screen_size:"27.69 cm (10.9 Inch)",
    os:"OS: ",
    os_type:"iPadOS",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/l0jwbrk0/tablet/h/l/f/-original-imagcbjgzhfak2jd.jpeg?q=70",
    title:"APPLE iPad Air (5th gen) 256 GB ROM 10.9 Inch with Wi-Fi+5G (Purple)",
    category:"tab"
  },
  {
    id: "tabapple05",
    brand: "Apple",
    rating: 4.6,
    price: 999,
    strike_price:1299,
    offer:23,
    processor:"Processor: ",
    processor_name:"M1 chip",
    ram:"RAM | SSD Storage: ",
    ram_type:"256GB ROM",
    screen:"Screen size: ",
    screen_size:"8.3 Inch",
    os:"OS: ",
    os_type:"iPadOS",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/ktop5e80/tablet/y/j/o/mk893hn-a-apple-original-imag6yg2hgqafged.jpeg?q=70",
    title:"APPLE iPad mini (6th Gen) 256 GB ROM 8.3 inch with Wi-Fi+5G (Space Grey)",
    category:"tab"
  },
  {
    id: "tablenovo06",
    brand: "Lenovo",
    rating: 4.3,
    price: 729,
    strike_price:999,
    offer:14,
    processor:"Processor: ",
    processor_name:"Unisoc T610 Octa Core Processor",
    ram:"RAM | SSD Storage: ",
    ram_type:"6GB RAM | 128 ROM",
    screen:"Screen size: ",
    screen_size:"11.5 Inch",
    os:"OS: ",
    os_type:"Android",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kl175ow0/tablet/t/1/x/za7d0021in-lenovo-original-imagy8w3ycyw2wm7.jpeg?q=70",
    title:"Lenovo Tab P11 Pro 6 GB RAM 128 GB ROM 11.5 inch with Wi-Fi+4G Tablet (Slate Grey)",
    category:"tab"
  },
  {
    id: "tabsamsung07",
    brand: "SAMSUNG",
    rating: 4.5,
    price: 579,
    strike_price:899,
    offer:27,
    processor:"Processor: ",
    processor_name:"Snapdragon 700 Series",
    ram:"RAM | SSD Storage: ",
    ram_type:"64GB ROM",
    screen:"Screen size: ",
    screen_size:"12.4 Inch",
    os:"OS: ",
    os_type:"Android",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kq5iykw0/tablet/i/x/z/sm-t735nzsainu-samsung-original-imag48ffsvjayz3x.jpeg?q=70",
    title:"SAMSUNG Galaxy Tab S7 64 GB ROM 12.4 inches with Wi-Fi+4G Tablet (Silver)",
    category:"tab"
  },
  {
    id: "taboneplus08",
    brand: "OnePlus",
    rating: 4.6,
    price: 479,
    strike_price:599,
    offer:7,
    processor:"Processor: ",
    processor_name:"Mediatek Dimensity 9000",
    ram:"RAM | SSD Storage: ",
    ram_type:"12GB RAM | 256 ROM",
    screen:"Screen size: ",
    screen_size:"11.61 Inch",
    os:"OS: ",
    os_type:"Android",
    warranty:"Warranty: ",
    warranty_years:"1 Year Limited Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/c/s/v/opd2203-oneplus-original-imagzbd5h8ybgccv.jpeg?q=70",
    title:"OnePlus Pad 12 GB RAM 256 GB ROM 11.61 inch with Wi-Fi Only Tablet (Halo Green)",
    category:"tab"
  },
  {
    id: "tabrealme09",
    brand: "realme",
    rating: 4.4,
    price: 349,
    strike_price:499,
    offer:22,
    processor:"Processor: ",
    processor_name:"Qualcomm Snapdragon 695",
    ram:"RAM | SSD Storage: ",
    ram_type:"6GB RAM | 128 ROM",
    screen:"Screen size: ",
    screen_size:"11 Inch",
    os:"OS: ",
    os_type:"Android 12",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/y/a/y/-original-imaggfrhvghucswf.jpeg?q=70",
    title:"realme Pad X 6 GB RAM 128 GB ROM 11 inch with Wi-Fi+5G Tablet (Glacier Blue)",
    category:"tab"
  },
  {
    id: "tabmotorola10",
    brand: "MOTOROLA",
    rating: 4.2,
    price: 249,
    strike_price:399,
    offer:15,
    processor:"Processor: ",
    processor_name:"MediaTek Helio G90T Octa-Core",
    ram:"RAM | SSD Storage: ",
    ram_type:"64 ROM",
    screen:"Screen size: ",
    screen_size:"11 Inch",
    os:"OS: ",
    os_type:"Android 11",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kyag87k0/tablet/4/n/o/g70-lte-moto-original-imagak3huz7jweyz.jpeg?q=70",
    title:"MOTOROLA tab g70 LTE 64 GB ROM 11 inch with Wi-Fi+4G Tablet (Modernist Teal)",
    category:"tab"
  },
  {
    id: "tabnokia11",
    brand: "Nokia",
    rating: 4.2,
    price: 200,
    strike_price:399,
    offer:45,
    processor:"Processor: ",
    processor_name:"Unisoc T606",
    ram:"RAM | SSD Storage: ",
    ram_type:"4GB RAM | 64GB ROM",
    screen:"Screen size: ",
    screen_size:"10.36 Inch",
    os:"OS: ",
    os_type:"Android 12",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/kvba7bk0/tablet/r/w/m/ta-1392-nokia-original-imag88wmgrhzzeyk.jpeg?q=70",
    title:"Nokia Tab T20 4GB RAM 64GB ROM 10.36 inch with Wi-Fi Only Tablet (Blue)",
    category:"tab"
  },
  {
    id: "tabhonor12",
    brand: "Honor",
    rating: 4.4,
    price: 230,
    strike_price:359,
    offer:17,
    processor:"Processor: ",
    processor_name:"Qualcomm Snapdragon 680",
    ram:"RAM | SSD Storage: ",
    ram_type:"6GB RAM | 128 ROM",
    screen:"Screen size: ",
    screen_size:"12 Inch",
    os:"OS: ",
    os_type:"Android 12",
    warranty:"Warranty: ",
    warranty_years:"1 Year Warranty",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/tablet/7/r/x/hey-w09-honor-original-imagg24vhgjym67v.jpeg?q=70",
    title:"Honor Pad 8 6 GB RAM 128 GB ROM 12 inch with Wi-Fi Only Tablet (Blue Hour)",
    category:"tab"
  },
// Headphones 
  {
    id: "headphonesennheiser01",
    brand: "Sennheiser",
    rating: 4.8,
    price: 449,
    strike_price:699,
    offer:20,
    bluetooth:"Bluetooth: ",
    bt_v:"5.2",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"60 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/c/v/n/509266-sennheiser-original-imagj79ew44h3vzf.jpeg?q=70",
    title:"Sennheiser Momentum 4 Wireless ANC Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonebeats02",
    brand: "Beats",
    rating: 3.9,
    price: 299,
    strike_price:399,
    offer:37,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"22 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/jvy4vbk0/headphone/d/z/n/beats-mrq82zm-a-original-imafgqhubwnzdyzq.jpeg?q=70",
    title:"Beats Studio3 Class 1, ANC Bluetooth Headset  (Defiant Black, Red, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonebose03",
    brand: "Bose",
    rating: 4.4,
    price: 279,
    strike_price:300,
    offer:7,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"20 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/krs40i80/headphone/6/s/q/noise-cancelling-700-bose-original-imag5gf6uyakqjgg.jpeg?q=70",
    title:"Bose NOISE CANCELLING HDPHS 700, Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonebeats04",
    brand: "Beats",
    rating: 4.2,
    price: 299,
    strike_price:499,
    offer:23,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"40 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/kiow6fk0-0/headphone/v/9/w/mrj82zm-a-beats-original-imafyfjyg7p3gwht.jpeg?q=70",
    title: "Beats MRJ82ZM/A Bluetooth Headset  (Grey, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonejbl05",
    brand: "JBL",
    rating: 3.8,
    price: 250,
    strike_price:699,
    offer:65,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"60 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/h/9/t/-original-imaguzgz4qjc5hnv.jpeg?q=70",
    title: "JBL Tour One M2, ANC, Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonesony06",
    brand: "SONY",
    rating: 4.6,
    price: 245,
    strike_price:599,
    offer:35,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"60 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/l1dwknk0/headphone/b/f/2/wh-1000xm4-sony-original-imagcywfhzq8hx2z.jpeg?q=70",
    title: "SONY WH-1000XM4 Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphoneslogitech07",
    brand: "Logitech",
    rating: 4.4,
    price: 149,
    strike_price:199,
    offer:5,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"10 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/l111lzk0/headphone/8/i/6/g733-lightspeed-rgb-logitech-original-imagcznej6g3z3th.jpeg?q=70",
    title:"Logitech G733 LIGHTSPEED RGB Bluetooth Headset  (Lilac, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonesphilips08",
    brand: "PHILIPS",
    rating: 3.4,
    price: 199,
    strike_price:259,
    offer:7,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"50 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/k5zn9u80/headphone/k/t/s/philips-taph805bk-original-imafzjzsns62zqvj.jpeg?q=70",
    title:"PHILIPS TAPH805BK/10 Wireless, ANC Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonejbl09",
    brand: "JBL",
    rating: 4,
    price: 99,
    strike_price:199,
    offer:50,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"20 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/kflftzk0pkrrdj/headphone-refurbished/g/n/u/u-quantum-200-jbl-original-imafw3z69hzxgynv.jpeg?q=70",
    title: "JBL Quantum 200 Wired Gaming Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonesmotorola10",
    brand: "MOTOROLA",
    rating: 3.4,
    price: 129,
    strike_price:229,
    offer:50,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery LIfe: ",
    bt_life:"15 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/jt4olu80/headphone/t/u/g/motorola-escape-800-anc-original-imafejrmhqpgufyh.jpeg?q=70",
    title: "MOTOROLA Escape 800 ANC Bluetooth Headset  (Black, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonesboat11",
    brand: "boAt",
    rating: 4.2,
    price: 99,
    strike_price:699,
    offer:75,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"30 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/kvsfhjk0/headphone/g/o/d/-original-imag8mf8xncrfjev.jpeg?q=70",
    title: "boAt Rockerz 450 Pro Bluetooth Headset  (White, On the Ear)",
    category:"headphone",
  },
  {
    id: "headphonesboat12",
    brand: "boAt",
    rating: 4.5,
    price: 50,
    strike_price:399,
    offer:70,
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"30 hours",
    img: "https://cdn1.smartprix.com/rx-i2sJltxjP-w1200-h1200/2sJltxjP.jpg",
    title: "boAt Rockerz 558 Wireless Headphones",
    category:"headphone",
  },
// Earbuds 
  {
    id: "earbudoppo01",
    brand: "OPPO",
    rating: 4.2,
    price: 49,
    strike_price:99,
    offer:50,
    play:"Playback: ",
    play_value:"10 min charge = 15 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"20 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/p/r/z/enco-buds-2-oppo-original-imagh9frfp7gxdb3.jpeg?q=70",
    title:
      "OPPO Enco Buds 2 with 28 hours Battery life (Midnight, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudrealme02",
    brand: "realme",
    rating: 4.2,
    price: 45,
    strike_price:99,
    offer:47,
    play:"Playback: ",
    play_value:"10 min charge = 20 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"25 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/h/2/k/-original-imaghe5mtuu35bhk.jpeg?q=70",
    title:
      "realme Techlife Buds T100 with 28 Hours Playback & AI ENC (Blue, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudoneplus03",
    brand: "OnePlus",
    rating: 4.3,
    price: 59,
    strike_price:99,
    offer:48,
    play:"Playback: ",
    play_value:"10 min charge = 40 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"40 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/w/t/q/-original-imagr4t8zuq2wzhe.jpeg?q=70",
    title:"OnePlus Nord Buds 2r in Ear Earbuds with Dual Mic (Deep Grey, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudnoise04",
    brand: "Noise",
    rating: 4,
    price: 19,
    strike_price:99,
    offer:73,
    play:"Playback: ",
    play_value:"10 min charge = 20 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"35 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/m/r/w/-original-imagsp8naj6v6ftm.jpeg?q=70",
    title: "Noise Buds VS404 with 50 Hours Playtime (Jet Black, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudboult05",
    brand: "Boult",
    rating: 4.1,
    price: 25,
    strike_price:99,
    offer:65,
    play:"Playback: ",
    play_value:"10 min charge = 30 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"20 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/z/v/y/-original-imagmuggusa94g3u.jpeg?q=70",
    title:"Boult Audio Z40 with Zen ENC Mic, 60H Battery Life (Blue, In the Ear)",
    category:"earbud",
  },
  {
    id: "earbudrealme06",
    brand: "realme",
    rating: 4.3,
    price: 39,
    strike_price:99,
    offer:60,
    play:"Playback: ",
    play_value:"10 min charge = 20 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"20 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/1/x/j/-original-imagsgfbgrfhy7vm.jpeg?q=70",
    title:"realme Buds Air 5 with 50dB ANC upto 38 hours (Deep Sea Blue, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudboat07",
    brand: "boAt",
    rating: 4,
    price: 19,
    strike_price:99,
    offer:80,
    play:"Playback: ",
    play_value:"10 min charge = 40 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"40 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/1/8/l/-original-imagqhswqgpwb2yu.jpeg?q=70",
    title: "boAt Airdopes 131 with upto 60 Hours (Active Black, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudnoise08",
    brand: "Noise",
    rating: 4.1,
    price: 20,
    strike_price:99,
    offer:79,
    play:"Playback: ",
    play_value:"10 min charge = 30 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"30 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/9/g/g/-original-imagufh6ghgms8nz.jpeg?q=70",
    title:"Noise Buds VS102 Neo with 40 Hrs Playtime (Carbon Black, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudrealme09",
    brand: "realme",
    rating: 4.3,
    price: 30,
    strike_price:99,
    offer:73,
    play:"Playback: ",
    play_value:"10 min charge = 20 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"30 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/v/y/o/-original-imagt3vwuweuwk9v.jpeg?q=70",
    title:"realme Buds T300 with 30dB ANC, 40 hours Playback   (Stylish Black, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudapple10",
    brand: "Apple",
    rating: 4.6,
    price: 279,
    strike_price:399,
    offer:30,
    play:"Playback: ",
    play_value:"10 min charge = 50 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"40 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/e/a/f/-original-imagtc44nk4b3hfg.jpeg?q=70",
    title:"AirPods Pro (2nd generation) with MagSafe Case (USB-C) (White, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudboult11",
    brand: "Boult",
    rating: 4.1,
    price: 29,
    strike_price:99,
    offer:67,
    play:"Playback: ",
    play_value:"10 min charge = 30 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"30 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/z/l/l/-original-imagty9c5pmq8tdt.jpeg?q=70",
    title: "Boult Audio Astra with 48Hrs Battery  (Smoky Metal, True Wireless)",
    category:"earbud",
  },
  {
    id: "earbudoneplus12",
    brand: "OnePlus",
    rating: 4.3,
    price: 32,
    strike_price:99,
    offer:70,
    play:"Playback: ",
    play_value:"10 min charge = 40 min play-time",
    range:"Range: ",
    range_value:"10 m",
    bluetooth:"Bluetooth: ",
    bt_v:"5.0",
    wm:"With mic: ",
    wm_ans:"Yes",
    Battery:"Battery Life: ",
    bt_life:"40 hours",
    img: "https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/0/v/m/nord-buds-2-oneplus-original-imagnwf7sgjetqwg.jpeg?q=70",
    title:"OnePlus Nord Buds 2 Earbuds with 25dB, ANC (Thunder Gray, True Wireless)",
    category:"earbud",
  },
];
